// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "planterBox":return img`
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
.........................
..ffffffffffffffffffff...
..feeeeeeeeeeeeeeeee1f...
..ffffffffffffffffffff...
..feeeeeeeeeeeeeeeeedf...
..ffeeeeeeeeeeeeeeedff...
...feeeeeeeeeeeeeeedf....
...ffeeeeeeeeeeeeeeff....
....feeeeeeeeeeeeedf.....
....feeeeeeeeeeeeedf.....
....ffeeeeeeeeeeedff.....
.....feeeeeeeeeeedf......
.....feeeeeeeeeeedf......
.....feeeeeeeeeeddf......
.....ffeeeeeeeeedff......
......feeeeeeeeedf.......
......ffffffffffff.......
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
